kind: Service
apiVersion: v1
metadata:
  name: nginx-secrets
  labels:
    app: nginx-secrets
spec:
  selector:
    app: nginx-secrets
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-secrets
  labels:
    app: nginx-secrets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-secrets
  template:
    metadata:
      labels:
        app: nginx-secrets
    spec:
      serviceAccountName: 
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "test-aws-secrets"
      containers:
      - name: nginx-secrets
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
